# MySql datasource
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    #name: driveSync
    url: jdbc:mysql://localhost:3306/batchtest
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
